// Auto-generated by `pnpm typegen` — do not edit manually.
// This stub file allows the build to pass before typegen runs.
// Run `pnpm typegen` after connecting a Sanity project to generate real types.

export type CompanyInfo = {
  _type: "companyInfo";
  _id: string;
  name?: string;
  tagline?: string;
  description?: string;
  ownerName?: string;
  ownerBio?: string;
  phone?: string;
  email?: string;
  address?: {
    city?: string;
    state?: string;
    country?: string;
    latitude?: number;
    longitude?: number;
  };
  serviceArea?: {
    description?: string;
    radiusMiles?: number;
  };
  licensingInfo?: {
    licenseNumber?: string;
    status?: string;
  };
  businessHours?: string;
  yearsExperience?: string;
  priceRange?: string;
  aggregateRating?: number;
  reviewCount?: number;
  logoUrl?: string;
  seo?: {
    metaTitle?: string;
    metaDescription?: string;
  };
};

export type EmailTemplates = {
  _type: "emailTemplates";
  _id: string;
  fromEmail?: string;
  toEmails?: string[];
  businessNotification?: {
    subject?: string;
    body?: string;
  };
  submitterConfirmation?: {
    subject?: string;
    body?: string;
  };
};
